# Site settings
title: Pastvre
email: joelle.maxwell@pastvre.net
description: > # this means to ignore newlines until "baseurl:"
  The homepage of Joelle "MooCovv" Maxwell.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.pastvre.net" # the base hostname & protocol for your site
github_username:  joellemaxw311

logo: /assets/images/pastvre.png
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

plugins:
  - jekyll-github-metadata
  - jekyll-avatar

repository: joellemaxw311

